apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main,master]'
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: go-application-sample
    appstudio.openshift.io/component: go-component-sample
    pipelines.appstudio.openshift.io/type: build
  name: go-component-sample-on-pull-request
  namespace: test
spec:
  params:
  - name: git-url
    value: '{{repo_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: docker.io/mm4eche/foobar:on-pr-{{revision}}
  - name: dockerfile
    value: docker/Dockerfile
  - name: path-context
    value: .
  pipelineRef:
    bundle: quay.io/redhat-appstudio-tekton-catalog/build-templates-bundle:32fe1b311a47774103c764fbf8407e10c64e5fae
    name: docker-build
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      status: {}
  - name: registry-auth
    secret:
      secretName: redhat-appstudio-registry-pull-secret
status: {}
